tasks:
    - name: "Startup"
      # First stop all gradle daemons that are (probably) stale.
      # Then, without initializing the caches, start one daemon and ensure
      # that the basic script startup works.
      before: |
          ./gradlew --stop
          ./gradlew --no-configuration-cache --rerun-tasks
          gp sync-done daemon_stop
      # For the prebuild we want it to work even if there are spotless problems
      # and we'll see those in the branch when we log in.
      init: ./gradlew spotlessApply build
      # Now remove any extant configuration cache due to a persistent issue
      # with spotless (see https://github.com/diffplug/spotless/issues/987).
      # Then we can do a quick build and be done.
      command: |
          rm -rf .gradle/configuration-cache
          gp sync-done confcache_removed
          ./gradlew build
github:
    prebuilds:
        master: true
        branches: true
image:
    file: .gitpod.Dockerfile
vscode:
    extensions:
        - esbenp.prettier-vscode
        - ilkka.google-java-format
        - k--kato.intellij-idea-keybindings
        - mathiasfrohlich.Kotlin
        - ms-azuretools.vscode-docker
        - redhat.java
        - redhat.vscode-xml
        - richardwillis.vscode-gradle
        - TabNine.tabnine-vscode
        - vscjava.vscode-java-debug
        - vscjava.vscode-java-dependency
        - vscjava.vscode-java-pack
        - vscjava.vscode-java-test
        - vscjava.vscode-maven
        - zxh404.vscode-proto3
