tabWidth: 4
printWidth: 80
useTabs: false
semi: false
overrides:
    - files:
          - "*.json"
          - "*.jsonc"
      options:
          tabWidth: 4
          parser: "json"
    - files: "*.md"
      options:
          proseWrap: "always"
    - files:
          - "*.yaml"
          - "*.yml"
      options:
          tabWidth: 2
