# Based on https://github.com/actions/starter-workflows/blob/main/ci/gradle.yml

name: CI System

on:
    push:
        branches: [$default-branch]
    pull_request:
        branches: [$default-branch]

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.0
              with:
                  all_but_latest: true
                  access_token: ${{ github.token }}
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"
            - name: Cache Gradle packages
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew build
            - name: Junit Report
              uses: ashley-taylor/junit-report-annotations-action@1.3
              if: always()
              with:
                  access-token: ${{ secrets.GITHUB_TOKEN }}
            - name:
                  Cleanup Gradle Cache
                  # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
                  # Restoring these files from a GitHub Actions cache might cause problems for future builds.
              run: |
                  rm -f ~/.gradle/caches/modules-2/modules-2.lock
                  rm -f ~/.gradle/caches/modules-2/gc.properties
